import { ReactNode } from 'react'; // Import ReactNode type
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Bag from "../components/Bag";
import { ClientProvider } from "./redux/provider"; 
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Add type annotation for 'children'
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex gap-1 font-cabin w-full bg-lightblue">
          <ClientProvider>  {/* Wrap everything inside ClientProvider */}
            <Navbar />
            <ToastContainer
              position="bottom-right"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
            />
            {children}
            <Bag />  {/* Place Bag inside ClientProvider */}
          </ClientProvider>
        </div>
      </body>
    </html>
  );
}
