import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Bag from "@/components/Bag";
import {ClientProvider} from "./redux/provider"; 
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
    
  
      <div className="flex gap-1 font-cabin w-full bg-lightblue ">
        <Navbar></Navbar>
        <ToastContainer
        position="bottom-right" // Set position to bottom-left
        autoClose={3000} // Optional: Adjust auto-close timing
        hideProgressBar={false} // Optional: Show or hide the progress bar
        newestOnTop={false} // Optional: Show newest toasts on top
        closeOnClick={false} // Optional: Close toast on click
        rtl={false} // Optional: Right-to-left text layout
        pauseOnFocusLoss // Optional: Pause toast on focus loss
        draggable // Optional: Allow dragging of the toast
        pauseOnHover // Optional: Pause on hover
      />
        <ClientProvider >
        {children} 
        <Bag></Bag>
        </ClientProvider>
      </div>
    ,

      </body>
    </html>
  );
}
